# Generated by Django 5.1.5 on 2025-01-18 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('check_interval_seconds', models.IntegerField(default=300)),
                ('expected_status_code', models.IntegerField(default=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('up', 'Up'), ('down', 'Down')], max_length=10)),
                ('response_time_ms', models.IntegerField()),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('status_change', models.BooleanField(default=False)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='monitor.site')),
            ],
        ),
    ]
