# Generated by Django 5.1.5 on 2025-01-19 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_webhook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='check_interval_seconds',
        ),
    ]
